# Generated by Django 4.1.11 on 2024-06-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
