# Generated by Django 4.1.11 on 2024-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_file_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='splitted_image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='splitted_pdf_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
