# Generated by Django 4.1.11 on 2024-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_pages_splitted_image_path_pages_splitted_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='splitted_image_path',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='splitted_pdf_path',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
